### ISSUE TITLE
cant start bitchat via npm start

### ISSUE THREAD

**Issue by Pepoliopo** [unwriter/bitchat#1]
no clue why, log file content attached

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bitchat@0.0.5~prestart: bitchat@0.0.5
6 info lifecycle bitchat@0.0.5~start: bitchat@0.0.5
7 verbose lifecycle bitchat@0.0.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle bitchat@0.0.5~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Pepolio\bitchat-master\node_modules\.bin;C:\Users\Pepolio\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Pepolio\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs\;C:\Users\Pepolio\AppData\Local\Microsoft\WindowsApps;C:\Users\Pepolio\AppData\Roaming\npm
9 verbose lifecycle bitchat@0.0.5~start: CWD: C:\Users\Pepolio\bitchat-master
10 silly lifecycle bitchat@0.0.5~start: Args: [ '/d /s /c', 'npm install; node env; node index' ]
11 silly lifecycle bitchat@0.0.5~start: Returned: code: 1  signal: null
12 info lifecycle bitchat@0.0.5~start: Failed to exec start script
13 verbose stack Error: bitchat@0.0.5 start: `npm install; node env; node index`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid bitchat@0.0.5
15 verbose cwd C:\Users\Pepolio\bitchat-master
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error bitchat@0.0.5 start: `npm install; node env; node index`
22 error Exit status 1
23 error Failed at the bitchat@0.0.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

System is Win10 64 bit

**Comment by loudbinary** [comment]
Ive seen this package fix a many issue for other node issues on windows 

https://www.npmjs.com/package/windows-build-tools
